Potential fix for failing test
My previous test was failing because...

```
=== Failed
=== FAIL: internal/provider TestAccTFENoCodeModule_with_variable_options (30.04s)
    resource_tfe_no_code_module_test.go:54: Step 1/1 error: Error running apply: exit status 1

        Error: Error creating no-code module for registry module mod-WZcEexVCnHFn2rk1: unprocessable content

        variable "freetext_string_emptylist" not found in source

          with tfe_no_code_module.sensitive,
          on terraform_plugin_test.tf line 33, in resource "tfe_no_code_module" "sensitive":
          33: 	resource "tfe_no_code_module" "sensitive" {

DONE 53 tests, 1 skipped, 1 failure in 335.793s
```

i.e.
https://github.com/svc-team-tf-core-cloud/terraform-random-module/blob/main/variables.tf
does not actually include my two imaginary variables

Rather than modifying the module to add more variables, instead I'll
just re-use the existing variables.

This also means I can't re-use the existing test case, but that's
probably a good thing to be honest.

As I do not have the relevant TFC Admin permissions to run these tests
locally myself, I'll rely on the CI to test it